### PR TITLE
handling hash as view_columns

### PR DESCRIPTION
**Pull request by ajahongir**
handling custom column

``` ruby
@view_columns ||= {
  'first_name' => 'User.first_name',
  'bio' => 'User.bio'
}
```

### CODE REVIEW

**Comment by antillas21** [comment]
@ajahongir 

I like what you've done so far in this PR. I just recently had a chance to review it and play with it in a sample test app.

I specifically love how you re-structured code here: https://github.com/ajahongir/ajax-datatables-rails/commit/92640dc93c70a3eae0e4df0ddc4c372377efb8c6

Now, here comes the tricky part (or "the catch"). From what I understand in the dataTables plugin documentation, you have options (emphasis on this) when declaring how your data is coming so you can populate a datatable. You can have your data coming in a 2D array, or a hash of hashes as you're implementing it here.

Well, I think it would be great if we provide that same flexibility when declaring the "ruby" version of the datatable class. I would not like to constrain users (as I have done so far, I am learning my lesson) to always declare the `view_columns` method either as a 2D array or as hash of hashes.

What I would like is to allow them to declare it in any of these two ways; let them choose, as datatables (the jQuery plugin) allows them.

So, for instance, these two samples should end-up working the same:

``` ruby
# app/datatables/exhibit_a.rb
class ExhibitA < AjaxDatatablesRails::Base
  def view_columns
    @view_columns ||= ["User.email", "User.username", "User.first_name", "User.last_name"]
  end
end

# app/datatables/exhibit_b.rb
class ExhibitB < AjaxDatatablesRails::Base
  def view_columns
    @view_columns ||= {
      { "email" => "User.email" },
      { "username" => "User.username" },
      { "fName" => "User.first_name" },
      { "lName" => "User.last_name" }
    }
  end
end

# Obviously, a customization in the `data` method is required for each case
# but, you are to expect that, given how you declare your `view_columns`
```

I know this represents that we should check how `view_columns` are declared and adjust accordingly, but given the work you've already done creating those classes for `Column, Datatable`, the changes can be isolated to the `Column` class and that's it.

A great move (extracting code to a class, as you've done) will allow us to provide this flexibility.

What do you think? Really looking forward to your comments.

**Comment by ajahongir** [comment]
@antillas21

> So, for instance, these two samples should end-up working the same:

well I will change to support of two way defining.

ps: in last wersion I define view_columns as:

``` ruby
class DirectionDatatable < AjaxDatatablesRails::Base
  def view_columns
    @view_columns ||= {
      id: { source: "Flight.id", cond: :eq },
      departure_date: { source: "Flight.departure_date", cond: :gteq },
      arrival_date: { source: "Flight.arrival_date", cond: :lteq },
      code: { source: "Flight.code" },
      direction: { source: "Flight.direction_id", cond: :eq }
    }
  end
end
```

this gives me to easy build custom searchs on client side:

dashboard

**Comment by ajahongir** [comment]
in this way I define not all of fields - only those which I want to sort or search on it. I think its handy. It way to binding client side columns with server side columns.

**Comment by ajahongir** [comment]
``` ruby
# app/datatables/exhibit_a.rb
class ExhibitA < AjaxDatatablesRails::Base
  def view_columns
    @view_columns ||= ["User.email", "User.username", "User.first_name", "User.last_name"]
  end
end
```

In this way if you want to define sorting to last column - you have to define all of prev. columns - and you have to check all time when you add a new columns at client side.

**Comment by antillas21** [comment]
@ajahongir The example you include is plain awesome! :)

Yeah, I'm all in for providing users with more fine-grained controls, but let's remember that sometimes you just need to implement something quickly that "just works" without so much hassle, and that's where the 2D array version can come in handy.

For those times when my table is simple, and I want the "least amount of typing I can do" to have it working, I can use the 2D array syntax ;) ... and when I need to have fine-grained control on what I want, that's when I can resort to the hash of hashes and all options as needed syntax.

**Comment by ajahongir** [comment]
@antillas21  We can do support 2D defining but I am afraid that in this case custom searching will not support.

so we will support 2 way defining view_columns:
1. simple defining - 2D. supports: ordering
2. custom defining  - Hash. supports: custom searching, ordering

ps: If you want to build easy table you can leave `view_columns = {}` as empty(not binded)

**Comment by antillas21** [comment]
Hey @ajahongir .... I'd like to apologize for all the time that took me to check and manually test your PR... I have been a little swamped with work, but should have taken time to look into this.

Apologies aside, I'd like to thank you for this _major surgery_ you've done to the codebase :)
I think the abstractions extracted will greatly help to keep the code tidy. All that is needed now, is to re-wire specs to ensure things work as expected, but I can take it from there.

Thanks again for your time, effort and contribution. I have no words to thank you enough.
Have a great day!

**Comment by ajahongir** [comment]
thank you for receipting a request. I wanted to release those features which we talked about.

**Comment by ajahongir** [comment]
the example project - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by antillas21** [comment]
:+1: on this.... we can use this repo as a reference whenever people has questions about similar scenarios.

Thanks for this @ajahongir :smile:

**Comment by ajahongir** [comment]
@antillas21 Iam making some improvments on v-0-4-0(https://github.com/ajahongir/ajax-datatables-rails/tree/filtering-improvements). some changes on flltering(searching). so if you have any time to look at it I appreciate..

**Pull request merged**
