### PR TITLE
fixed params hash deprecation warning, …

### PR DESCRIPTION
**Pull request by SampsonCrowley**
and changed tests to use actionparams instead of hash with indifferent access

### CODE REVIEW

**Comment by SampsonCrowley** [comment]
I would suggest that we change this branch name to `v0.4` to allow for patch updates without having to rename the branch afterwards

**Comment by matissg** [comment]
@SampsonCrowley  I'm trying to implement your fix, however when I navigate to my json file I see this error: `undefined method to_unsafe_h for nil:NilClass`
Do you have any idea what could be wrong, please?

**Comment by SampsonCrowley** [comment]
@matissg not sure. what is your version of rails? I have been using this commit I've pull requested without issue.

**Comment by SampsonCrowley** [comment]
@matissg how are you implementing the fix? and which method is throwing the error?

**Comment by SampsonCrowley** [comment]
to_unsafe_h is an `ActionParameter` method. if you're not calling it on a `params` object, that would cause the issue

**Comment by matissg** [comment]
@SampsonCrowley  I'm using Rails 5.1. and I did download full gem file pack with your fix. Don't remember which method was causing the error as I downgraded back to 0.3.1. version with another fix for params. I'd rather upgrade to the latest 0.4.1. version though. How do I implement that `to_unsafe_h` on `params` object, please? Can you give some example?

**Comment by SampsonCrowley** [comment]
What do you mean you downloaded the gem file pack?

Point your gem file to my fork on github. why do the work I've already done?

⁣Sent from BlueMail ​

**Comment by matissg** [comment]
@SampsonCrowley  To be honest I'm new here and did not know how to grab gem file from you :) I would use your code, however I need your help with that `to_unsafe_h` as I did not get how to use it with params.

**Comment by SampsonCrowley** [comment]
I cant really help without some sort of code or without knowing how your using it.

Here's a page on how to install a gem from github

http://stackoverflow.com/questions/2823492/install-gem-from-github-branch

**Comment by matissg** [comment]
@SampsonCrowley  This one I know and tried to understand how to point to some branch. I just [opened this](https://github.com/antillas21/ajax-datatables-rails/tree/99f973d40b90ee8cbfc844e4971250e1d23d1f8a) and grabbed files from there. Can you, please, point to correct location where I can get latest gem version with the fix?
Regarding `to_unsafe_h` I did not call it on params anyhow. Can you give me some example, how should I use it, please? So far I just did everything as [in this tutorial](https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to) , but it did not work for me.

**Comment by ajahongir** [comment]
>So far I just did everything as in this tutorial , but it did not work for me.

I have already updated my branch so if you will try remove gem and run bundle again it should work.

**Comment by matissg** [comment]
@ajahongir Ok, thank you, I'll try to do it. Should I be using that `params.to_unsafe_h` somehwere in my Controller, or else? @SampsonCrowley  mentioned I should be calling on params somehow. So far I thought I just install the gem and that's it.

**Comment by SampsonCrowley** [comment]
You dont. You pass context and let the gem handle mapping the parameters

**Comment by n-rodriguez** [comment]
Hi! Thank you but this is now fixed : https://github.com/n-rodriguez/ajax-datatables-rails/pull/216/commits/594058c524da90af0e82814a139c5d480dc55324

**Comment by SampsonCrowley** [comment]
@n-rodriguez and the Travis CI build error doesn't bother you? My build passes all tests

**Comment by SampsonCrowley** [comment]
and still allows using map instead of having to use each and push individually to an array (which is an O(n) operation BTW)

**Comment by n-rodriguez** [comment]
> which is an O(n) operation BTW)

Your point, my bad.

**Comment by n-rodriguez** [comment]
Merged : https://travis-ci.org/n-rodriguez/ajax-datatables-rails/builds/231358123
Thank you!

**Pull request closed without merging**
