### PR TITLE
Make search case-insensitive

### PR DESCRIPTION
**Pull request by garrettlancaster**
Hi, I think most people would prefer a case-insensitive search (since users rarely bother to capitalize search terms).   All I've done is change the LIKE query to ILIKE.

Cheers,
Garrett

P.S.  Great gem, by the way; definitely saved me a good bit of time :)

### CODE REVIEW

**Comment by JoelQ** [comment]
@garrettlancaster Thanks for your suggestion. `ilike` is postgres specific however and I want to be able to support other databases. Perhaps something at the model level that would use ruby's `downcase` method would be a better solution.

**Comment by garrettlancaster** [comment]
Does that look like a better solution? I think it's much more efficient than trying to convert huge numbers of fields in ruby.

**Comment by JoelQ** [comment]
That is better but case insensitive search will still only work for postgres users. I think a solution where `downcase` was called on the search term before being passed into the query and `LOWER(column_name)` was used in the query would be more database-agnostic. Something along the lines of:

``` ruby
query = @searchable_columns.map do |column| 
  "LOWER(#{column}) LIKE :search"
end.join(" OR ")
records = records.where(query, search: "%#{params[:sSearch].downcase}%")
```

This way we are guaranteed to be checking a lowercase string against a lowercase string. What do you think?

**Comment by garrettlancaster** [comment]
Hmm..I know MySQL `LIKE` defaults to case-insensitive, but not sure about others.

The only issue I see with the `lower()` solution is the bypassing of any indexes on `column`.  I know you can specifically create a lower case index in postgres: `CREATE INDEX lower_title_idx ON films ((lower(title)));`, 
though I have no idea how to use it via rails.  Other than that, it does feel a little cleaner.

EDIT:  It looks like you would have to change the schema format for the rails app to :sql and perform raw sql via `execute` in the migrations to add the `lower()` index.  Makes it much less appealing IMO

**Comment by JoelQ** [comment]
Hmm... I see your point. Do you have an alternative that would allow case-insensitive search and be database agnostic?

**Comment by garrettlancaster** [comment]
Well, one option would be to drop down to Arel and use `matches`.  That's what the squeel gem (https://github.com/ernie/squeel) does, so you could even just use squeel and not hassle with it.

**Comment by mcfadden** [comment]
:+1:  Helpful gem, but because it's case sensitive it changes the behavior of the filter vs non server-side processing. From the user's perspective, nothing should change.

**Comment by JoelQ** [comment]
I'm crazy busy at the moment and don't have the time to look into implementing case-insensitive search using Arel. If one of you would like to do so and make a pull request, that would be great. Otherwise this feature will need to wait until I can get around to it.

**Comment by antillas21** [comment]
Hi @garrettlancaster and @mcfadden,

I just became the maintainer for this gem.

I would like to close this PR and invite to check the changes we have in store for this project (to be released soon).

**Comment by antillas21** [comment]
@garrettlancaster, @mcfadden  ... just to let you know that a new version has been released.

This is a link to the [changelog](https://github.com/antillas21/ajax-datatables-rails/blob/master/CHANGELOG.md), so you can see what's new.

Also... about the issue of case-insensitive search... please take a look [here](https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L70-L105) to get an idea on how searching has been made "database agnostic" as long as you use `ActiveRecord` as ORM.

**Pull request closed without merging**
