### PR TITLE
Added some functionality

### PR DESCRIPTION
**Pull request by zpaulovics**
- multi column sort
- multi terms search
- paggination option all -> '-1'

### CODE REVIEW

**Comment by antillas21** [comment]
@zpaulovics can you provide a small spec on the logic behind these changes?

**Comment by zpaulovics** [comment]
Hi, 

In my current project I use the datatables both in serverSide way and in none server side way. For small reports the none server side solution works perfectly. The client side datatables provides the multi-sort and the multi-search features as well as the all option for pagination. It is very confusing for the end users if some of the table behaviors are different.
1. Sorting: with the client side datatables you can select a sort column, then by pressing the shift key you can add second, third, etc. columns as additional sorting criteria. The serverSide implementation currently cannot do the same. 
2. Search: with the client side datatables when you enter more then one terms (words) to the search field, it will select a particular row if one of the term is matching with a column, but the other term is matching with another column.  For instance if you want to see in your list those rows, which has a particular course-type which is allocated to a particular teacher you need the multi-search function, and this is how the client side solution works. The serverSide implementation currently cannot do the same and will result different selected rows. This different behavior is very confusing in one application.
3. Pagination: the all option is available as standard datatables feature. You may need it for tableTools extension, when you want to export to excel or to produce a printed copy of your report. The server side implementation now raises an exception if you try to use the 'all' pagination option. 

The implemented features in this pull request extend the functionality of your awesome gem, and make it to behave in the same way as the client side version. It would be nice of you if you could accept it and merge it to the repository. 

Regards, Zoltan

**Comment by antillas21** [comment]
@zpaulovics ooh I am most interested and willing to merge your contribution to the gem :smile: . I just need to understand the reason and scenario behind these changes.

Currently, I can not auto-merge this code because I made a small change yesterday (Sunday, for me) to address an old issue where `searchable_columns` included a non text/string based field. So, you will have to pull the latest commits into your branch, solve any conflicts, and push again to this pull request, so I can cleanly merge this.

Don't worry for broken specs (on current functionality), I still need to figure out how to rewrite them so I can have a rails-y setup to test the dependency on `Arel`.

Thanks again for your effort and contribution to this gem.

**Comment by zpaulovics** [comment]
Before I pushed this pull request, I have pulled your master repo into my repo. I may did something wrong to have this conflict with your change. After I have sent my pull request I recognized the conflict. Let's see how we can resolve the conflict. Please, let me know if I can do anything for that.

**Comment by antillas21** [comment]
@zpaulovics done! Resolved conflicts and merged.

Now, I'll just have to schedule some time this coming weekend to work on fixing the specs.

**Comment by zpaulovics** [comment]
Great! Thank you:-)

**Pull request merged**
