### PR TITLE
Search in column and global together

### PR DESCRIPTION
**Pull request by mmagnusek**
#258

### CODE REVIEW

**Comment by diesl** [comment]
Would be really cool to finally get this functionality 👍

**Comment by mauriciopasquier** [comment]
Thank you for this pull request! Just tested it on my project <3

**Comment by diesl** [comment]
Still, it would be great to have this merged!

@mmagnusek Some checks in Travis are failing, is there are chance you can fix them?

**Comment by n-rodriguez** [comment]
@mmagnusek hi there! thanks for your work! can you please rebase your branch on `master` and see what it says in CI?

**Comment by n-rodriguez** [comment]
@mmagnusek thank you!

**Pull request merged**
