### PR TITLE
use get_raw_record_count for iTotalRecords

### PR DESCRIPTION
**Pull request by nickmerwin**
Otherwise it uses the full table count.

### CODE REVIEW

**Comment by JoelQ** [comment]
Thank you for for contributing to the project. Unfortunately, I am no longer maintaining it. If you are interested in taking over the project, pleas let me know.

**Comment by antillas21** [comment]
@nickmerwin,

I just became the maintainer for this gem.

I would like to close this PR and invite to check the changes we have in store for this project (to be released soon).

**Comment by antillas21** [comment]
@nickmerwin  ... just to let you know that a new version has been released.

This is a link to the [changelog](https://github.com/antillas21/ajax-datatables-rails/blob/master/CHANGELOG.md), so you can see what's new.

Also... about record count for `iTotalRecords`, take a look [here](https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L36-L43) to see how it has been resolved.

**Comment by nickmerwin** [comment]
ok thank you @antillas21 !

**Pull request closed without merging**
