### PR TITLE
Order NULL values last

### PR DESCRIPTION
**Pull request by natebird**
This is a change to the order query to always order NULL values last. The SQL is generic.

### CODE REVIEW

**Comment by ajahongir** [comment]
is this solution for all sql bd?

**Comment by n-rodriguez** [comment]
Hi! Thanks for your patch! Can you please add a test that covers this case? Also, it would be nice if this behavior could be parameterized and not the default behavior.

**Comment by natebird** [comment]
Yep! I'll see what I can do. Thanks!

**Comment by natebird** [comment]
Closing in preference to #242

**Pull request closed without merging**
