### PR TITLE
Oracle support?

### PR DESCRIPTION
**Pull request by antillas21**
Hi @lutechspa

Would like to ask if these two small commits allow to use `Oracle` as db engine with this gem?

If so, would you be interested in us merging this back to the gem?

### CODE REVIEW

**Comment by lutechspa** [comment]
Hi @antillas21

I don't guarantee that it works on all versions of Oracle, but for mine (Oracle 11g)  it works!
If you want, proceed with merge.

Thanks for the great work

**Comment by antillas21** [comment]
I see...

Could you share any sample datatable implementation after adding these two commits? Say, suppose you are using Oracle 11g, could you share in a gist:
- a sample `Gemfile`
- a sample datatable class
- a sample `initializers/ajax-datatables-rails.rb` file
- a sample html + js code using this datatable class
- a sample controller action using the datatable class
- a copy+paste of the controller/action calls in the `log` file for the following:
  - on initial call to retrieve data,
  - after searching any term,
  - after clicking any column to sort results,
  - after clicking any pagination control
- any other code you consider relevant to make it work

I am aware that this may seem excessive, but we were considering to add support for Oracle, though had no idea how complicated this can be. So, your response that it works on a certain version is a good start :) and want to make sure it can point us in the right direction (if not solving the issue already).

What do you say? Really looking forward to your comments.

**Comment by lutechspa** [comment]
Hi @antillas21 

Sorry for delay....

Unfortunately i can't share my code, because the software that it use the ajax datatable is under my company copyright, i'm sorry.

Don't worry
I create a simple project, in my personal repository, which reproduces the same logic implemented in my private software

https://github.com/paoloripamonti/oracle-ajax-datatable

 It's a very very simple project.

if you want to test it yuo can download a free version of oracle (http://www.oracle.com/technetwork/database/database-technologies/express-edition/overview/index.html)

I hope I was helpful, if you want other details please contact me on my personal repository.

Thanks

**Comment by antillas21** [comment]
@lutechspa Awesome! Thank you very much for this :smile: 

No problemo about not being able to share the original code, that was never my intention, that's why for each item (in my long list) I prepended the word _sample_, but definitively the repo you provide is a much, much clearer example, and is more helpful.

Thanks again. I will merge this into master, update the `README` to hint users that with such a small config this can work on Oracle (I would like to add a link to the repo you created to illustrate the example, if that's OK with you), credit you in the `CHANGELOG`, and make a point release.

**Comment by antillas21** [comment]
@lutechspa here are the latest changes (after the merge)
- [CHANGELOG](https://github.com/antillas21/ajax-datatables-rails/blob/master/CHANGELOG.md#031)
- [README](https://github.com/antillas21/ajax-datatables-rails#what-if-im-using-oracle)

Thanks for your contribution.

**Pull request merged**
