### PR TITLE
filtering improvements

### PR DESCRIPTION
**Pull request by ajahongir**

### CODE REVIEW

**Comment by zedalaye** [comment]
+1. Works great for me (over branch v-0-4-0)

**Comment by ajahongir** [comment]
@antillas21 If you have any chance to look this. please review this request, Could we accept this request on 0.4 verion?

**Comment by ajahongir** [comment]
@mebezac

**Comment by ajahongir** [comment]
finally I have finished this request which contains changes as:
- code refactoring
- supporting RMI 1.9.3-2.3.0
- released sorting and searching functions - now supports multi sorting and searching.
- fixed and updated specs
- updated readme
- updated sample [project](https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to)
- fixed [counting](https://github.com/antillas21/ajax-datatables-rails/pull/118) issue

**Comment by ajahongir** [comment]
@antillas21 It will be nice If you have any change to look this changes

**Comment by ajahongir** [comment]
https://github.com/antillas21/ajax-datatables-rails/pull/118

**Comment by ajahongir** [comment]
@antillas21 Hey, could we merge this request into?

**Pull request merged**
