### PR TITLE
Add support for trilogy adapter for MySQL #422

### PR DESCRIPTION
**Pull request by mrudult**
Adds support for trilogy [adapter](https://github.com/trilogy-libraries/activerecord-trilogy-adapter) in Rails >= 6 and <= 7.0.

Rails 7.1 includes trilogy as a built-in adapter and makes it default in Rails 8 - https://github.com/rails/rails/pull/47880, https://rubyonrails.org/2023/10/5/Rails-7-1-0-has-been-released

### CODE REVIEW

**Review by antillas21 — APPROVED** [review]
LGTM

**Comment by mrudult** [comment]
It looks like making `trilogy` default (and built-in in Rails 7.1) is [pushed back](https://github.com/trilogy-libraries/trilogy/issues/26) as it doesn't yet support `caching_sha2_password` password auth. Thus, adding back the dependency to rails 7.1 gemfile.

**Review by antillas21 — APPROVED** [review]

**Comment by naoyanickf** [comment]
plz merge this...this is very important

**Review by n-rodriguez — APPROVED** [review]

**Comment by naoyanickf** [comment]
@n-rodriguez thank you so much!

**Pull request merged**
